[build]
  command = "npm run build:seo"
  publish = "dist"

# Production context: all deploys from the main branch
[context.production]
  command = "npm run build:seo"

# Deploy Preview context: deploys from pull/merge requests
[context.deploy-preview]
  command = "npm run build:seo"

# Branch deploy context: deploys from branches other than main
[context.branch-deploy]
  command = "npm run build:seo"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:;" 